#---------------------------------- CHATGPT

version: '3.8'

services:
  drupal:
    image: drupal:latest 
    restart: always
    ports:
      - "8003:80" 
    environment:
      DRUPAL_DB_HOST: db
      DRUPAL_DB_USER: drupal_user
      DRUPAL_DB_PASSWORD: drupal_pass
      DRUPAL_DB_NAME: drupal_db
    volumes:
      - drupal-modules:/var/www/html/modules # Drupal modules directory
      - drupal-profiles:/var/www/html/profiles # Drupal profiles directory
      - drupal-themes:/var/www/html/themes # Drupal themes directory
      - drupal-sites:/var/www/html/sites # Drupal sites directory

  db:
    image: mariadb:10.6.4-focal
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: drupal_db
      MYSQL_USER: drupal_user
      MYSQL_PASSWORD: drupal_pass
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  drupal-modules:
  drupal-profiles:
  drupal-themes:
  drupal-sites:



#---------------------------------- LINODE 
version: '3.3'

services:
  drupal:
    image: drupal:latest
    ports:
      - 80:80
    volumes:
      - drupal_modules:/var/www/html/modules
      - drupal_profiles:/var/www/html/profiles
      - drupal_themes:/var/www/html/themes
      - drupal_sites:/var/www/html/sites
    restart: always

  postgres:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: your_postgres_password
    volumes:
        - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  drupal_modules:
  drupal_profiles:
  drupal_themes:
  drupal_sites:
  db_data:

#---------------------------------- 
